server:
  port: 8090
spring:
  mail:
    username: 1462718182@qq.com  #修改为自己的邮箱
    password: bjfwqtyzytuphajb  #授权码（第三步中生成的授权码）
    host: smtp.qq.com  #发送邮件的服务主机
    properties:
      mail: 
        smtp: 
          ssl: 
            enable: true  #开启ssl安全
  datasource:
    username: root 
    password: root  #修改为自己的数据库密码
    driver-class-name: com.mysql.jdbc.Driver

    url: jdbc:mysql://localhost:3306/staff?useUnicode=true&characterEncoding=UTF-8&useSSL=false

mybatis:
  # 指定全局配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
 
  
logging:
   level:
     com.ibm.springboot.controller.LoggingController: trace  #设置输出级别

# 1.不指定路径时会在当前项目下生成springboot.log日志
# 2.可以指定完整的路径,如：D:/springboot.log
   file: springboot.log
  
# 在当前磁盘的根路径下创建spring文件夹和里面的log文件夹;
#使用 spring.log 作为默认文件;
#当file和path同时使用时,以file为准
   path: /spring/log
   
#  在控制台输出的日志的格式   
   pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n'
# 指定文件中日志输出的格式    
    file: '%d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} === - %msg%n'
    